(in-package :immutable-hash-map)

(define-symbol-macro empty-hash-map empty-immutable-hash-table)
(setf (symbol-function 'hash-map) #'immutable-hash-table)
(setf (symbol-function 'alist-to-hash-map) #'alist-to-immutable-hash-table)
(setf (symbol-function 'hash-map-p) #'immutable-hash-table-p)
(setf (symbol-function 'empty-p) #'immutable-hash-table-empty-p)
(setf (symbol-function 'count) #'immutable-hash-table-count)
(setf (symbol-function 'has-key) #'immutable-hash-table-has-key)
(setf (symbol-function 'ref) #'immutable-hash-table-ref)
(setf (symbol-function 'keys) #'immutable-hash-table-keys)
(setf (symbol-function 'vals) #'immutable-hash-table-values)
(setf (symbol-function 'items) #'immutable-hash-table-items)
(setf (symbol-function 'add) #'immutable-hash-table-add)
(setf (symbol-function 'remove) #'immutable-hash-table-remove)
(setf (symbol-function 'union) #'immutable-hash-table-union)
(setf (symbol-function 'intersection) #'immutable-hash-table-intersection)
(setf (symbol-function 'difference) #'immutable-hash-table-difference)
(setf (symbol-function 'symmetric-difference) #'immutable-hash-table-symmetric-difference)
