(in-package :set)

(setf (symbol-function 'set) #'immutable-set)
(setf (symbol-function 'set-p) #'immutable-set-p)
(setf (symbol-function 'empty-p) #'immutable-set-empty)
(setf (symbol-function 'count) #'immutable-set-count)
(setf (symbol-function 'member) #'immutable-set-member)
(setf (symbol-function 'complement) #'immutable-set-complement)
(setf (symbol-function 'add) #'immutable-set-add)
(setf (symbol-function 'remove) #'immutable-set-remove)
(setf (symbol-function 'complement) #'immutable-set-complement)
(setf (symbol-function 'union) #'immutable-set-union)
(setf (symbol-function 'intersection) #'immutable-set-intersection)
(setf (symbol-function 'difference) #'immutable-set-difference)
(setf (symbol-function 'symmetric-difference) #'immutable-set-symmetric-difference)
(setf (symbol-function 'sub-super) #'immutable-set-sub-super)
(setf (symbol-function 'set-equal) #'immutable-set-equal)
(setf (symbol-function 'disjoint) #'immutable-set-disjoint)
(setf (symbol-function 'distinct) #'immutable-set-distinct)
(setf (symbol-function 'set-to-list) #'immutable-set-to-list)
(setf (symbol-function 'list-to-set) #'list-to-immutable-set)
(setf (symbol-function 'fmap) #'immutable-set-fmap)
(setf (symbol-function 'fapply) #'immutable-set-fapply)
(setf (symbol-function 'product) #'immutable-set-product)
(setf (symbol-function 'flatmap) #'immutable-set-flatmap)
(setf (symbol-function 'flatten) #'immutable-set-flatten)
(setf (symbol-function 'in-set) #'immutable-set-to-seq)
(setf (symbol-function 'first) #'immutable-set-first)
(setf (symbol-function 'rest) #'immutable-set-rest)
(setf (symbol-function 'set-fmap) #'immutable-set-fmap)
(setf (symbol-function 'set-pure) #'immutable-set-pure)
(setf (symbol-function 'set-product) #'immutable-set-product)
(setf (symbol-function 'set-fapply) #'immutable-set-fapply)
(setf (symbol-function 'set-flatmap) #'immutable-set-flatmap)
(setf (symbol-function 'set-flatten) #'immutable-set-flatten)
(setf (symbol-function 'make-set-context) #'make-immutable-set-context)

(define-symbol-macro empty-set empty-immutable-set)
