(in-package :immutable-hash-terse-set)

(setf (symbol-function 'set) #'immutable-set)
(setf (symbol-function 'set-p) #'immutable-set-p)
(setf (symbol-function 'set-empty-p) #'immutable-set-empty)
(setf (symbol-function 'set-count) #'immutable-set-count)
(setf (symbol-function 'set-member) #'immutable-set-member)
(setf (symbol-function 'set-add) #'immutable-set-add)
(setf (symbol-function 'set-remove) #'immutable-set-remove)
(setf (symbol-function 'set-complement) #'immutable-set-complement)
(setf (symbol-function 'set-union) #'immutable-set-union)
(setf (symbol-function 'set-intersection) #'immutable-set-intersection)
(setf (symbol-function 'set-difference) #'immutable-set-difference)
(setf (symbol-function 'set-symmetric-difference) #'immutable-set-symmetric-difference)
(setf (symbol-function 'set-sub-super) #'immutable-set-sub-super)
(setf (symbol-function 'set-equal) #'immutable-set-equal)
(setf (symbol-function 'set-disjoint) #'immutable-set-disjoint)
(setf (symbol-function 'set-distinct) #'immutable-set-distinct)
(setf (symbol-function 'set-to-list) #'immutable-set-to-list)
(setf (symbol-function 'list-to-set) #'list-to-immutable-set)

(define-symbol-macro empty-set empty-immutable-set)
